name: 签到

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 1-59 * * * *
  watch:
    types: started

jobs:
  build:
    env:
      COOKIES: ${{ secrets.COOKIES }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 签到
      run: |
        pip install -r requirements.txt
        python3 checkin.py